### ISSUE TITLE
Cannot connect, CORS error

### ISSUE THREAD

**Issue by jack-ii** [UnJavaScripter/web-serial-example#3]
Unfortunately it does not work.
The connect button does nothing and i get these error messages before i click anything.
-Arduino Nano v3.0 ATmega168 CH340G
-Chrome portable 99.0.4844.82
![0](https://user-images.githubusercontent.com/81538128/159575506-694de79b-77f2-4869-9231-2c186ae604c9.png)
Or am I doing something wrong?
Does "Run the demo app locally" mean to open the index.html in the browser? Or do I have to do something with the ts files?

**Comment by funnierinspanish** [comment]
Hi @jack-ii . You should serve the index.html file from a _server_. Any testing server will do the job, such as [http-server](https://www.npmjs.com/package/http-server), [Python http server](https://docs.python.org/3/library/http.server.html). You can use more complex stuff like IIS or WAMP, but the result will be the same.

The typescript files already transpiled to javascript inside the `dist` folder, so it should work without messing with them.

**Comment by jack-ii** [comment]
Thanks! :) I just found out a minute ago that it works from a server. Because your demo site and others work. The Run locally confused me.
Firefox is not supported right?
And I noticed that the button to led delay is a little slow.
When I press the button, a blue LED on the Arduino lights up immediately, but the actual action is only executed ~1 second later.
This is slower than when I press a button on the Smarthone via WiFi to router to an ESP. Is it possible to make it faster or does it take time to connect etc.?

**Comment by funnierinspanish** [comment]
Glad you made it work! It seems like I need to improve the readme :)

Indeed, Firefox has decided [not to implement it](https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API#browser_compatibility) (yet?) you can check [this GitHub](https://github.com/mozilla/standards-positions/issues/336) issue for more details if you have some time to spare.
